# https://developers.home-assistant.io/docs/apps/configuration#app-configuration
name: "GPS Data Echo App"
version: "1.0.0"
slug: test123
description: "Echoes GPS data from gpsd application to the shell using u-blox 7 receiver"
url: "https://github.com/meowx3/ha-addons/tree/main/test123"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  gps_device: "/dev/ttyACM0"
  baud_rate: 9600
schema:
  gps_device: "str?"
  baud_rate: "int?"
image: "ghcr.io/meowx3/test123"
