name: "GPS NTP Server"
version: "1.0.1"
description: "Offline NTP server using GPSD and Chrony with PPS support"
slug: "gps-ntp-simple"
arch:
  - aarch64
  - amd64
options:
  gps_device: "/dev/ttyUSB0"
  pps_device: "/dev/pps0"
  baud_rate: "9600"
  enable_pps: false
  gnss_constellations: "GPS,GLONASS,Galileo"
  update_interval: 1 # Hz
  drift_calibration: 0.0
#privileged: true
