---
name: GPS-NTP
description: "My other newest broken change?!"
version: dev
slug: gps-ntp
url: https://github.com/meowx3/ha-addons/gps-ntp
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
panel_icon: mdi:clock
ports:
  123/udp: 123
ports_description:
  123/udp: NTP Port

options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)

image: ghcr.io/meowx3/gps-ntp
