---
name: GPS-NTP
description: "My other newest broken change?!"
version: 1.0.1
slug: gps-ntp
url: https://github.com/meowx3/ha-addons/gps-ntp
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
panel_icon: mdi:clock
ports:
  123/udp: 123
  8080/tcp: 8080
ports_description:
  123/udp: NTP Server Port
  8080/tcp: Web Dashboard Port

options:
  log_level: info
  gps_receiver:
    device: /dev/ttyACM1
    baudrate: 9600
    timeout: 10
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  gps_receiver:
    device: str?
    baudrate: int?
    timeout: int?

image: ghcr.io/meowx3/gps-ntp
